# Generated by Django 4.1.7 on 2023-05-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('images', models.JSONField()),
                ('trailer', models.JSONField()),
                ('title', models.CharField(max_length=100)),
                ('title_english', models.CharField(max_length=100, null=True)),
                ('title_japanese', models.CharField(max_length=100, null=True)),
                ('episodes', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('airing', models.BooleanField()),
                ('aired', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('score', models.FloatField(null=True)),
                ('scored_by', models.IntegerField(null=True)),
                ('favorites', models.IntegerField()),
                ('synopsis', models.TextField(null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Anime',
                'db_table': 'anime_anime',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anime_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anime_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anime_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anime_studio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anime_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'anime_review',
                'ordering': ['pk'],
            },
        ),
    ]
