# Generated by Django 4.1.7 on 2023-03-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'managed': False, 'verbose_name': 'anime', 'verbose_name_plural': 'anime'},
        ),
    ]
