# Generated by Django 4.1.7 on 2023-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('images', models.JSONField()),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'db_table': 'anime_character',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MAIN', 'Main'), ('SUPP', 'Supporting')], default='MAIN', max_length=4)),
            ],
            options={
                'db_table': 'anime_role',
                'managed': False,
            },
        ),
    ]
