# Generated by Django 4.1.7 on 2023-03-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'managed': False, 'ordering': ['pk'], 'verbose_name': 'anime', 'verbose_name_plural': 'anime'},
        ),
    ]
