# Generated by Django 4.1.7 on 2023-03-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('favorites', models.IntegerField()),
                ('images', models.JSONField()),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'db_table': 'character',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
    ]
