# Generated by Django 4.1.7 on 2023-04-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'managed': False, 'ordering': ['pk'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Anime'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pk'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
