# Generated by Django 4.1.7 on 2023-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_favorites_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date_joined',
            new_name='date_added',
        ),
    ]
