# Generated by Django 4.1.7 on 2023-03-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_options'),
        ('user', '0006_rename_date_joined_score_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='rated',
            field=models.ManyToManyField(blank=True, to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
