# Generated by Django 4.1.7 on 2023-03-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_favorites_user_rated_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rated',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
