# Generated by Django 4.1.7 on 2023-03-23 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_rated_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_friends', models.BooleanField(blank=True, default=False)),
                ('user_is_being_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_article_set', to=settings.AUTH_USER_MODEL)),
                ('user_is_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_article_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
